// Generated by pnpm brand:generate; edit scripts/generate-brand.mjs.
'use client';

import { useId, type SVGProps } from 'react';

type BrandLogoProps = Omit<SVGProps<SVGSVGElement>, 'children'> & { title?: string };

export default function BrandLogo({ title, width = 44, height = 44, ...props }: BrandLogoProps) {
  const id = 'webomok-' + useId().replace(/:/g, '');
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width={width} height={height}
      role={title ? 'img' : undefined} aria-hidden={title ? undefined : true}
      aria-labelledby={title ? id + '-title' : undefined} focusable="false" {...props}>
      {title && <title id={id + '-title'}>{title}</title>}
      <defs>
  <linearGradient id={`${id}-slate`} x2="1" y2="1"><stop stopColor="#263449"/><stop offset="1" stopColor="#020617"/></linearGradient>
  <linearGradient id={`${id}-gold`} x2="1" y2="1"><stop stopColor="#fff0b5"/><stop offset=".45" stopColor="#d9ad59"/><stop offset="1" stopColor="#906027"/></linearGradient>
  <linearGradient id={`${id}-wood`} x2=".8" y2="1"><stop stopColor="#f1d39b"/><stop offset=".5" stopColor="#d6a763"/><stop offset="1" stopColor="#b58042"/></linearGradient>
  <radialGradient id={`${id}-black`} cx=".32" cy=".24" r=".75"><stop stopColor="#606774"/><stop offset=".35" stopColor="#252b36"/><stop offset=".8" stopColor="#090c13"/><stop offset="1" stopColor="#02040a"/></radialGradient>
  <radialGradient id={`${id}-pearl`} cx=".32" cy=".22" r=".85"><stop stopColor="#fff"/><stop offset=".45" stopColor="#f6f3e9"/><stop offset=".8" stopColor="#cdd2da"/><stop offset="1" stopColor="#8994a5"/></radialGradient>
  <radialGradient id={`${id}-shine`}><stop stopColor="#fff" stopOpacity=".8"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></radialGradient>
  <filter id={`${id}-shadow`} x="-40%" y="-40%" width="180%" height="190%"><feDropShadow dx="0" dy="2" stdDeviation="1.6" floodColor="#020617" floodOpacity=".65"/></filter>
  <clipPath id={`${id}-board`}><rect x="7" y="7" width="37" height="50" rx="5"/></clipPath>
</defs>
<rect x="1" y="1" width="62" height="62" rx="14" fill={`url(#${id}-slate)`}/>
<rect x="1.5" y="1.5" width="61" height="61" rx="13.5" fill="none" stroke={`url(#${id}-gold)`} strokeOpacity=".65"/>
<rect x="7" y="7" width="37" height="50" rx="5" fill={`url(#${id}-wood)`} filter={`url(#${id}-shadow)`}/>
<g clipPath={`url(#${id}-board)`} fill="none" stroke="#835323" strokeWidth=".5" opacity=".24">
  <path d="M10 5c-3 12 4 21 0 34s2 17 1 22M15 4c-4 14 5 27 1 39s1 14 0 20M20 4c-3 10 3 18 0 27s4 19 1 30M27 3c4 14-4 22 0 36s-2 15 0 23M33 4c-3 12 3 21 0 33s3 20 1 24M39 3c3 11-4 25 0 36s-1 18 1 22"/>
</g>
<path d="M16 10v44M28 10v44M40 10v44M10 16h31M10 28h31M10 40h31M10 52h31" fill="none" stroke="#61431f" strokeWidth=".75" opacity=".68"/>
<circle cx="28" cy="40" r="1.25" fill="#61431f"/>
<g filter={`url(#${id}-shadow)`}>
  <circle cx="19" cy="22" r="10.5" fill={`url(#${id}-black)`} stroke="#677080" strokeWidth=".5"/>
  <ellipse cx="16" cy="17" rx="5" ry="2.8" fill={`url(#${id}-shine)`} transform="rotate(-28 16 17)"/>
  <circle cx="33" cy="38" r="10.5" fill={`url(#${id}-pearl)`} stroke="#fff6dc" strokeWidth=".5"/>
  <ellipse cx="30" cy="33" rx="5.5" ry="3" fill={`url(#${id}-shine)`} transform="rotate(-28 30 33)"/>
</g>
<path d="M48 23h10M52 23l-2 17M48 30h8v10M47 40h12" fill="none" stroke="#020617" strokeWidth="3.5" strokeLinejoin="round" strokeLinecap="round" opacity=".6" transform="translate(0 1)"/>
<path d="M48 23h10M52 23l-2 17M48 30h8v10M47 40h12" fill="none" stroke={`url(#${id}-gold)`} strokeWidth="2" strokeLinejoin="round" strokeLinecap="round"/>
<path d="M49 48h8" stroke={`url(#${id}-gold)`} strokeWidth="1" opacity=".65"/>
    </svg>
  );
}
