import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';

const require = createRequire(import.meta.url);
const sharp = require(require.resolve('sharp', { paths: [require.resolve('next')] }));
const artwork = `<defs>
  <linearGradient id="slate" x2="1" y2="1"><stop stop-color="#263449"/><stop offset="1" stop-color="#020617"/></linearGradient>
  <linearGradient id="gold" x2="1" y2="1"><stop stop-color="#fff0b5"/><stop offset=".45" stop-color="#d9ad59"/><stop offset="1" stop-color="#906027"/></linearGradient>
  <linearGradient id="wood" x2=".8" y2="1"><stop stop-color="#f1d39b"/><stop offset=".5" stop-color="#d6a763"/><stop offset="1" stop-color="#b58042"/></linearGradient>
  <radialGradient id="black" cx=".32" cy=".24" r=".75"><stop stop-color="#606774"/><stop offset=".35" stop-color="#252b36"/><stop offset=".8" stop-color="#090c13"/><stop offset="1" stop-color="#02040a"/></radialGradient>
  <radialGradient id="pearl" cx=".32" cy=".22" r=".85"><stop stop-color="#fff"/><stop offset=".45" stop-color="#f6f3e9"/><stop offset=".8" stop-color="#cdd2da"/><stop offset="1" stop-color="#8994a5"/></radialGradient>
  <radialGradient id="shine"><stop stop-color="#fff" stop-opacity=".8"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>
  <filter id="shadow" x="-40%" y="-40%" width="180%" height="190%"><feDropShadow dx="0" dy="2" stdDeviation="1.6" flood-color="#020617" flood-opacity=".65"/></filter>
  <clipPath id="board"><rect x="7" y="7" width="37" height="50" rx="5"/></clipPath>
</defs>
<rect x="1" y="1" width="62" height="62" rx="14" fill="url(#slate)"/>
<rect x="1.5" y="1.5" width="61" height="61" rx="13.5" fill="none" stroke="url(#gold)" stroke-opacity=".65"/>
<rect x="7" y="7" width="37" height="50" rx="5" fill="url(#wood)" filter="url(#shadow)"/>
<g clip-path="url(#board)" fill="none" stroke="#835323" stroke-width=".5" opacity=".24">
  <path d="M10 5c-3 12 4 21 0 34s2 17 1 22M15 4c-4 14 5 27 1 39s1 14 0 20M20 4c-3 10 3 18 0 27s4 19 1 30M27 3c4 14-4 22 0 36s-2 15 0 23M33 4c-3 12 3 21 0 33s3 20 1 24M39 3c3 11-4 25 0 36s-1 18 1 22"/>
</g>
<path d="M16 10v44M28 10v44M40 10v44M10 16h31M10 28h31M10 40h31M10 52h31" fill="none" stroke="#61431f" stroke-width=".75" opacity=".68"/>
<circle cx="28" cy="40" r="1.25" fill="#61431f"/>
<g filter="url(#shadow)">
  <circle cx="19" cy="22" r="10.5" fill="url(#black)" stroke="#677080" stroke-width=".5"/>
  <ellipse cx="16" cy="17" rx="5" ry="2.8" fill="url(#shine)" transform="rotate(-28 16 17)"/>
  <circle cx="33" cy="38" r="10.5" fill="url(#pearl)" stroke="#fff6dc" stroke-width=".5"/>
  <ellipse cx="30" cy="33" rx="5.5" ry="3" fill="url(#shine)" transform="rotate(-28 30 33)"/>
</g>
<path d="M48 23h10M52 23l-2 17M48 30h8v10M47 40h12" fill="none" stroke="#020617" stroke-width="3.5" stroke-linejoin="round" stroke-linecap="round" opacity=".6" transform="translate(0 1)"/>
<path d="M48 23h10M52 23l-2 17M48 30h8v10M47 40h12" fill="none" stroke="url(#gold)" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>
<path d="M49 48h8" stroke="url(#gold)" stroke-width="1" opacity=".65"/>`;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 64 64">${artwork}</svg>\n`;
await writeFile('public/favicon.svg', svg);
// Generate real inline JSX, with per-instance IDs to support repeated badges.
const jsx = artwork
  .replace(/([a-z]+)-([a-z]+)=/g, (_, a, b) => `${a}${b[0].toUpperCase()}${b.slice(1)}=`)
  .replace(/id="([^"]+)"/g, 'id={`${id}-$1`}')
  .replace(/"url\(#([^\)]+)\)"/g, '{`url(#${id}-$1)`}');
await writeFile('src/components/BrandLogo.tsx', `// Generated by pnpm brand:generate; edit scripts/generate-brand.mjs.\n'use client';\n\nimport { useId, type SVGProps } from 'react';\n\ntype BrandLogoProps = Omit<SVGProps<SVGSVGElement>, 'children'> & { title?: string };\n\nexport default function BrandLogo({ title, width = 44, height = 44, ...props }: BrandLogoProps) {\n  const id = 'webomok-' + useId().replace(/:/g, '');\n  return (\n    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width={width} height={height}\n      role={title ? 'img' : undefined} aria-hidden={title ? undefined : true}\n      aria-labelledby={title ? id + '-title' : undefined} focusable="false" {...props}>\n      {title && <title id={id + '-title'}>{title}</title>}\n      ${jsx}\n    </svg>\n  );\n}\n`);

const sizes = [[16, 'favicon-16x16.png'], [32, 'favicon-32x32.png'], [48, 'favicon-48x48.png'], [180, 'apple-touch-icon.png'], [192, 'icon-192.png'], [512, 'icon.png']];
const pngs = new Map();
for (const [size, name] of sizes) {
  const png = await sharp(Buffer.from(svg)).resize(size, size).png().toBuffer();
  pngs.set(size, png);
  await writeFile('public/' + name, png);
}
// PNG-compressed ICO entries are supported by modern browsers and Windows.
const entries = [16, 32, 48].map(size => ({ size, png: pngs.get(size) }));
const header = Buffer.alloc(6 + entries.length * 16);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(entries.length, 4);
let offset = header.length;
entries.forEach(({ size, png }, index) => {
  const pos = 6 + index * 16;
  header[pos] = size;
  header[pos + 1] = size;
  header.writeUInt16LE(1, pos + 4);
  header.writeUInt16LE(32, pos + 6);
  header.writeUInt32LE(png.length, pos + 8);
  header.writeUInt32LE(offset, pos + 12);
  offset += png.length;
});
await writeFile('src/app/favicon.ico', Buffer.concat([header, ...entries.map(entry => entry.png)]));
// Verify all raster exports and ICO directory dimensions during regeneration.
for (const [size, name] of sizes) {
  const info = await sharp(await readFile('public/' + name)).metadata();
  if (info.width !== size || info.height !== size) throw new Error('Invalid icon: ' + name);
}
console.log('Generated inline logo, SVG, six PNGs and 16/32/48px ICO.');
